### ISSUE TITLE
major refactor

### ISSUE THREAD

**Issue by iCodeSometime** [iCodeSometime/candidate#8]
- [ ] Write more tests
- [ ] Expose the underlying bitboards in a more consistent way
- [ ] Split up PieceType::legals
- [ ] #4
- [ ] Rename `Board` as `Position`
- [ ] Split the project into independent game, position, and magic crates
- [ ] ...
